### ISSUE TITLE
CoA request not implemented

### ISSUE THREAD

**Issue by errno** [wichert/pyrad#2]
I'm trying to build small pyrad based application for sending CoA (RFC5176) requests to Cisco ASR.

This is my code:

```python
    import pyrad.packet
    from pyrad.client import Client
    from pyrad.dictionary import Dictionary
    
    srv = Client(server="172.16.x.x", secret="secret", dict=Dictionary("standard", "cisco"))
    
    req = srv.CreatePacket(code=pyrad.packet.CoARequest, User_Name="errno", Cisco_Account_Info="S172.16.x.x", Cisco_AVPair="subscriber:command=account-logoff")
    
    reply = srv.SendPacket(req)
    
    if reply.code == pyrad.packet.CoAACK:
        print "Ok"
    else:
        print "Fail"
```

When I run it, traceback appears:

    Traceback (most recent call last):
      File "rad-comand.py", line 9, in <module>
        reply = srv.SendPacket(req)
      File "/usr/local/lib/python2.6/dist-packages/pyrad/client.py", line 161, in SendPacket
        return self._SendPacket(pkt, self.acctport)
      File "/usr/local/lib/python2.6/dist-packages/pyrad/client.py", line 123, in _SendPacket
        self._socket.sendto(pkt.RequestPacket(), (self.server, port))
    AttributeError: 'Packet' object has no attribute 'RequestPacket'

I had fast look through source and found than 'RequestPacket' method implemented only for AcctPacket and AuthPacket, what class must be used for CoA request (packet code 43)?

I'm using latest pyrad-2.0 from PyPi.

**Comment by mstendorf** [comment]
Did this ever get solved?

**Comment by GIC-de** [comment]
CoA requests should work using my fork of pyrad https://github.com/GIC-de/pyrad and the following example code: 
```Python
from pyrad.client import Client, Timeout
from pyrad.dictionary import Dictionary

client = Client(server="NAS IP", secret="SECRET", authport=3799, acctport=3799, dict=Dictionary("PATH TO DICT"))

client.timeout = 3
client.retries = 3

attributes = { ... attributes ... }     # RADIUS attributes

request = client.CreateAcctPacket(code=43, **attributes)
result = client.SendPacket(request)
```

**Comment by GIC-de** [comment]
coa request working (aef95f92a)
