### ISSUE TITLE
Python3 bytecompiling error

### ISSUE THREAD

**Issue by cicku** [wichert/pyrad#20]
Hi,

I'm maintaining this package in Fedora, something not correct now:

Bytecompiling .py files below /home/rpmaker/rpmbuild/BUILDROOT/python-pyrad-2.0-1.fc20.i386/usr/lib/python2.7/ using /usr/bin/python2.7
Bytecompiling .py files below /home/rpmaker/rpmbuild/BUILDROOT/python-pyrad-2.0-1.fc20.i386/usr/lib/python3.3/ using /usr/bin/python3.3
*** Error compiling '/home/rpmaker/rpmbuild/BUILDROOT/python-pyrad-2.0-1.fc20.i386/usr/lib/python3.3/site-packages/pyrad/curved.py'...
  File "/usr/lib/python3.3/site-packages/pyrad/curved.py", line 38
    def datagramReceived(self, datagram, (host, port)):
                                         ^
SyntaxError: invalid syntax

error: Bad exit status from /var/tmp/rpm-tmp.XQLy85 (%install)

**Comment by jlaine** [comment]
This is the patch we use in Debian:

http://anonscm.debian.org/viewvc/python-modules/packages/pyrad/trunk/debian/patches/python3.patch?view=markup

**Comment by GIC-de** [comment]
fixed in b4d849b17
