### ISSUE TITLE
pyrad.server accepting requests (packets) from any NAS

### ISSUE THREAD

**Issue by marzsv** [wichert/pyrad#45]
Is there a way that a pyrad server respond to packets sent from any host, I don't know in advance what the IP addresses of the "remote hosts" are.

I've tried passing a RemoteHost with the IP address 0.0.0.0/0 (this works in FreeRADIUS), I also have tried not passing the `hosts` keyword argument to the pyrad.server.Server constructor... but it doesn't work.

Any workaround?

**Comment by onder07** [comment]
The problem continues. :(
