### ISSUE TITLE
send several instances of attribute with different tags failed

### ISSUE THREAD

**Issue by alexander-bespalov** [wichert/pyrad#47]
I'm trying to send several instances of attribute with different tags (using tagged attribute):

srv = Client(server=radius, secret=radius_secret, dict=Dictionary("dictionary"))
req = srv.CreateAuthPacket(code=pyrad.packet.AccessRequest, User_Name=username)
req["User-Password"] = req.PwCrypt(password)
req["ERX-Service-Activate:3"] = 'test3'
req["ERX-Service-Activate:8"] = 'test8'
reply = srv.SendPacket(req)

But only one (the last) instance is sending to RADIUS server:

Received Access-Request Id 90 from 127.0.0.1:50116 to 127.0.0.1:1812 length 59
        User-Name = 'user1'
        User-Password = 'test'
        ERX-Service-Activate:8 = 'test8'

**Comment by alexander-bespalov** [comment]
Seems the problem access-request only. Tried coa-request - multiple tagged instances of the same attribute are sending just fine.

**Comment by GIC-de** [comment]
Sending is possible if you do it this way:

```
srv = Client(server=radius, secret=radius_secret, dict=Dictionary("dictionary"))

attributes = {"User-Name": username}
attributes["User-Password"] = req.PwCrypt(password)
attributes["ERX-Service-Activate:3"] = 'test3'
attributes["ERX-Service-Activate:8"] = 'test8'

req = srv.CreateAuthPacket(code=pyrad.packet.AccessRequest, **attributes)
reply = srv.SendPacket(req)
```
