### ISSUE TITLE
has_tag attribute implementation

### ISSUE THREAD

**Issue by pobept** [wichert/pyrad#5]
How can I send a query whose attributes contain the has_tag, as defined in RFC2868. 

example:
User-Name := "redback"
Service-Name:1 += "RSE-SVC-DIDNTPAY"
Service-Action:1 += 1
Service-Parameter:1 += "InterimTime=900"
Service-Name:2 += "RSE-SVC-INET"
Service-Action:2 += 1)
Service-Parameter:2 += "InterimTime=900 Rate=1024"

thanks

**Comment by GIC-de** [comment]
@pobept has_tag should work now. Please verify!
