### ISSUE TITLE
How to add vendor-specific attribute to a packet

### ISSUE THREAD

**Issue by sburnwal** [wichert/pyrad#75]
Hello, Thanks for implementing this pyrad as opensource.
I am trying to test a radius server by using this pyrad as a client and I am looking for how to include VSA attributes in a packet. 

Can you please give an example of how to add vendor-specific attribute to a packet ?
Tried things like this but did not work:
req['Vendor-Specific]['Cisco/Cisco-AVPair'] = "someattrvalue"
req['Vendor-Specific]['Cisco:Cisco-AVPair'] = "someattrvalue"
req['Cisco:Cisco-AVPair'] = "someattrvalue"
req['Cisco/Cisco-AVPair'] = "someattrvalue"

**Comment by sburnwal** [comment]
I got this resolved by using the VSA as done for attribute e.g.

req["Cisco-AVPair"] = "someattrvalue"

**Comment by AndreiSobolev** [comment]
Hello! Can you show me example code, how you add subattribute?
When i used this:
`req['Vendor-Specific'] = 'subscriber:command=account-logon'`
i get
`TypeError: startswith first arg must be str or a tuple of str, not bytes`
Thank you!

**Comment by baiyanling1** [comment]
How to add vendor-specific attribute to a packet   ，like  3GPP-IMEISV
