### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by omidkosari** [wichert/pyrad#8]
Any chance to implement IPv6 support in near future ? We can see ipv6addr and ipv6prefix bellow the comment "These datatypes are parsed but not supported:" .
Actually i am using v0.6 . it is fine just i want to add ipv6 support in it .
It is better for me not to upgrade to new version because my version is a modified version which included in IBSng project .

**Comment by GIC-de** [comment]
@omidkosari the following new types are implemented now. Please check if this works for you.

ipv6addr    16 octets in network byte order
ipv6prefix  18 octets in network byte order

**Comment by morrowc** [comment]
This change doesn't actually make pyrad ipv6 clean...

https://github.com/wichert/pyrad/blob/master/pyrad/client.py#L71

is still fixing the listener code to ipv4 only.
would a fix be useful here? :) (it would be to me)

**Comment by johnmyrda** [comment]
@morrowc I'd find a fix useful. The company I work for uses this library to test a RADIUS client/server implementation and the lack of an ipv6 listener makes it difficult to completely test the product's ipv6 support.

**Comment by morrowc** [comment]
Ok, also the link I sent above is the client code, the server code is similarly hobbled...

https://github.com/wichert/pyrad/blob/master/pyrad/server.py#L106

i'll work up a fix in the next few days.

**Comment by morrowc** [comment]
#61  is the open pull request to add server.py code for binding to ipv4 and ipv6 sockets.

The client code should need similar work, but I'm not sure it's as necessary as the server code.
